
version: "3.8"

services:
  backend:
    container_name: cagechat-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://user:password@db:5450/mydb
    env_file:
      - .env
    ports:
      - "10000:10000"
    depends_on:
      - db

  frontend:
    container_name: cagechat-frontend
    build:
      context: ./frontend_react/client
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    env_file:
      - .env

  db:
    container_name: cagechat-db
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5450:5450"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: